// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlgh7lbHAq2qW2aWRtF7MXviy9FJr6AwA',
    appId: '1:448711939310:web:291b4d08048ddcc1990fff',
    messagingSenderId: '448711939310',
    projectId: 'pertemuan-listview-c7cb7',
    authDomain: 'pertemuan-listview-c7cb7.firebaseapp.com',
    storageBucket: 'pertemuan-listview-c7cb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPR8eQv0P7Leeloana6Z3KGdI-5KBuTR8',
    appId: '1:448711939310:android:6d8f4eb9d75ba72d990fff',
    messagingSenderId: '448711939310',
    projectId: 'pertemuan-listview-c7cb7',
    storageBucket: 'pertemuan-listview-c7cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgHUmwvDdyRoykuvEiXXN8_yOwARh3WtQ',
    appId: '1:448711939310:ios:bdd363a2390eea1e990fff',
    messagingSenderId: '448711939310',
    projectId: 'pertemuan-listview-c7cb7',
    storageBucket: 'pertemuan-listview-c7cb7.firebasestorage.app',
    iosBundleId: 'com.example.pertemuanListview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgHUmwvDdyRoykuvEiXXN8_yOwARh3WtQ',
    appId: '1:448711939310:ios:bdd363a2390eea1e990fff',
    messagingSenderId: '448711939310',
    projectId: 'pertemuan-listview-c7cb7',
    storageBucket: 'pertemuan-listview-c7cb7.firebasestorage.app',
    iosBundleId: 'com.example.pertemuanListview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlgh7lbHAq2qW2aWRtF7MXviy9FJr6AwA',
    appId: '1:448711939310:web:4a0831eb139b0d2c990fff',
    messagingSenderId: '448711939310',
    projectId: 'pertemuan-listview-c7cb7',
    authDomain: 'pertemuan-listview-c7cb7.firebaseapp.com',
    storageBucket: 'pertemuan-listview-c7cb7.firebasestorage.app',
  );
}
